#pragma config(Sensor, dgtl1,  decodeleft,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  decoderight,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  StopButton,     TouchSensor)
#pragma config(Motor,  port1,           motorleft,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port10,          motorright,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	clearDebugStream();

	SensorType[in8] = sensorNone;
	delay(1000);
	SensorType[in8] = snesorGyro;
	delay(1000);

	if(SensorValue[in8] > 10) {
		motor[rightmotor] = 87;
	}

	else if (SensorValue[in8] < -10) {
		motor[leftmotor] = 87;
	}

	else if (SensorValue[StopButton] == 0) {
		motor[rightmotor] = 0;
		motor[leftmotor] = 0;
	}

	else {
		motor[rightmotor] = 127;
		motor[leftmotor] = 127;
	}

	writeDebugStreamLine("Sensor value; %d", SensorValue[in8]);

}
