#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           motorRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          motorLeft,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("DebugStream")

task main()
{
			clearDebugStream();
			SensorValue[leftEncoder] = 0;
			SensorValue[rightEncoder] = 0;
			motor[motorLeft] = 0;
			motor[motorRight] = 0;
			wait1Msec(6000);
			motor[motorLeft] = 60;
			motor[motorRight] = 60;
			wait1Msec(3000);
			writeDebugStreamLine("Sensor value: %d ", SensorValue[leftEncoder]);
			writeDebugStreamLine("Sensor value: %d ", SensorValue[rightEncoder]);


}
