#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma DebuggerWindows("DebugStream")

task main()
{
{
	clearDebugStream();
	SensorType[in8] = sensorNone;
 	wait1Msec(1000);
 	SensorType[in8] = sensorGyro;
 	wait1Msec(2000);
	int masterPower;
	int slavePower = masterPower;
	masterPower = SensorValue(motor[leftMotor]);
  slavePower = SensorValue(motor[rightMotor]);
  wait1Msec(1000);
  int tickGoal = (360 * (4)) / 26.4;
  int totalTicks = 0;
  int error = 0;
  int k = 10;

  SensorValue[leftEncoder] = 0;
  SensorValue[rightEncoder] = 0;

  while(abs(totalTicks) < tickGoal)
  {
    motor[leftMotor] = masterPower;
    motor[rightMotor] = slavePower;

    writeDebugStreamLine("Sensor value: %d ", SensorValue[in8]);
    writeDebugStreamLine("Sensor value: %d ", SensorValue[leftEncoder]);
		writeDebugStreamLine("Sensor value: %d ", SensorValue[rightEncoder]);

    error = SensorValue[sensorGyro];

    //slavePower = slavePower + (error / k);

    wait1Msec(100);

    totalTicks = totalTicks + SensorValue[sensorGyro];
  }
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}


}
