#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int leaderPower;
	int followerPower = leaderPower - 5;
	leaderPower = SensorValue(motor[leftMotor]);
  followerPower = SensorValue(motor[rightMotor]);
  int tickGoal = (360 * (400)) / 26.4;
  int totalTicks = 0;
  int error = 0;
  int k = 300000;
  waitUntil(vexRT[Btn7L]); {

	  SensorValue[leftEncoder] = 0;
	  SensorValue[rightEncoder] = 0;

	  while(abs(totalTicks) < tickGoal)
	  {
	  	totalTicks = (SensorValue[rightEncoder] + SensorValue[leftEncoder])/2;
	    motor[leftMotor] = leaderPower;
	    motor[rightMotor] = followerPower;

	    error = SensorValue[leftEncoder] - SensorValue[rightEncoder];

	    followerPower = followerPower + (error / k);

	    wait1Msec(100);

	  }
	  motor[leftMotor] = 0;
	  motor[rightMotor] = 0;
	}
}


}
